import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";

import { GithubIcon, ZagIcon } from "@/components/visualizer/controls/icons";
import { componentsMap } from "@/components/components-map";
import Link from "next/link";
import { ColorMode } from "@/components/color-mode";
import { Anatomy } from "@/components/anatomy";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Zag JS Visualizer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="page-header">
          <h1>Zag Visualizer</h1>
          <p>Explore Zag&apos;s state machines through interactive graphs</p>
          <div className="toolbar">
            <ColorMode />
            <Link
              href="https://github.com/anubra266/zag-visualizer"
              target="_blank"
              aria-label="Go to Zag Visualizer GitHub repository"
            >
              <GithubIcon />
            </Link>
            <Link
              href="https://github.com/chakra-ui/zag"
              aria-label="Go to Zag GitHub repository"
              target="_blank"
            >
              <ZagIcon />
            </Link>
          </div>
        </div>
        <div className="machine-list">
          {Object.entries(componentsMap).map(([key, { title }]) => {
            return (
              <Link key={key} href={`/${key}`} className="machine-item">
                <span>
                  {title}
                  <button
                    className="github-link"
                    onClick={() =>
                      window.open(
                        `https://github.com/chakra-ui/zag/blob/main/packages/machines/${key}/src/${key}.machine.ts`,
                        "_blank"
                      )
                    }
                  >
                    <GithubIcon />
                  </button>
                </span>
                <Anatomy component={key} />
              </Link>
            );
          })}
        </div>
      </main>
    </>
  );
}
